language: php
  - '7.0'
  - hhvm # on Trusty only
  - nightly
branches:
  only:
    - master
before_install:
  - travis_retry composer self-update
  - composer install
script: phpunit --bootstrap vendor/autoload.php test
